# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


count = 3
soma = 2
m = [1, 2, 3]
while m[2] < 4_000_000:
    count +=  1
    m[0] = m[1]
    m[1] = m[2]
    m[2] = m[0] + m[1]
    if not (m[2] % 2):
        soma += m[2]

print(soma)